# docker-compose.yml
services:
  backend:

    container_name: we-backend-1
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app/backend"
      - "./backend/logs:/app/backend/logs"
      -  "./data:/app/data"
    environment:
     - PYTHONUNBUFFERED=1
     - PYTHONPATH=/app
     - DATABASE_URL=${DATABASE_URL}